In [1]:
echo 'hello'

'hello'


In [2]:
# Manual normalization

def norm_manual(data):
    n_max = max(data)
    n_min = min(data)
    l_data = len(data)

    for i in range(0, l_data):
        data[i] = (data[i] - n_min) / (n_max - n_min)

    return data

In [3]:
nilai = [10, 13, 14, 12]
nilai_norm = norm_manual(nilai)
nilai_norm

[0.0, 0.75, 1.0, 0.5]

In [16]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [12]:
data = [[10,11], [11,12]]
data = np.asarray(data)
scaler = MinMaxScaler()

scaled = scaler.fit_transform(data)
scaled


array([[0., 0.],
       [1., 1.]])

In [13]:
data = [[10, 11, 12, 13, 15, 20, 9 ,18]]
data = np.asarray
scaler = MinMaxScaler()

scaled = scaler.fit_transform(data)
scaled

TypeError: float() argument must be a string or a real number, not 'builtin_function_or_method'

In [14]:
def stand_manual(data):
    n_mean = np.mean(data)
    n_std = np.std(data)
    l_data = len(data)

    for i in range(0, l_data):
        data[i] = (data[i] - n_mean) / n_std

    return data

In [15]:
nilai = [10, 11, 12, 14, 15, 18, 20]
nilai_std = stand_manual(nilai)
nilai_std

[-1.2565617248750867,
 -0.9633639890708998,
 -0.670166253266713,
 -0.08377078165833932,
 0.2094269541458475,
 1.0890201615584079,
 1.6754156331667815]

In [17]:
data = [[100, 0.001],
        [8, 0.05],
        [50, 0.005],
        [88, 0.07],
        [4, 0.1]]

print("Data asli:")
print(data)

scaler = MinMaxScaler()

print("Data transform hasil normalisasi:")

scaled = scaler.fit_transform(data)
print(scaled)

Data asli:
[[100, 0.001], [8, 0.05], [50, 0.005], [88, 0.07], [4, 0.1]]
Data transform hasil normalisasi:
[[1.         0.        ]
 [0.04166667 0.49494949]
 [0.47916667 0.04040404]
 [0.875      0.6969697 ]
 [0.         1.        ]]


In [26]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder()

oe = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektro Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Padang'],
    ['Politeknik Negeri Bandung']
]

poly_oh = oh.fit_transform(oe)
poly_oh.toarray()

array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.]])

In [27]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer()

oe = [
    {'name' : 'POLINEMA'},
    {'name' : 'PENS'},
    {'name' : 'POLBAN'},
    {'name' : 'PNJ'},
    {'name' : 'POLIJE'}
]

poly_dv = dv.fit_transform(oe)
poly_dv.toarray()

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [28]:
corpus = [
            'the house had a tiny little mouse',
            'the cat saw the mouse',
            'the mouse ran away from the house',
            'the cat finally ate the mouse',
            'the end of the mouse story'
]

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words = 'english')
response = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out(response))

['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']
